- name: Создать директорию /opt/korotkosilka
  file:
    path: /opt/korotkosilka
    state: directory
    mode: 0755

- name: Создать директорию для сертификатов
  file:
    path: /opt/korotkosilka/certs
    state: directory
    mode: 0755

- name: Сгенерировать приватный ключ для сертификата
  community.crypto.openssl_privatekey:
    path: /opt/korotkosilka/certs/privkey.pem
    size: 2048
    type: RSA
    mode: 0600

- name: Сгенерировать самоподписанный сертификат
  community.crypto.x509_certificate:
    path: /opt/korotkosilka/certs/fullchain.pem
    privatekey_path: /opt/korotkosilka/certs/privkey.pem
    provider: selfsigned
    subject: '/CN=korotko.local'
    days: 365
    mode: 0644

- name: Копировать docker-compose файл
  copy:
    src: files/docker-compose.frontend_backend.yml
    dest: /opt/korotkosilka/docker-compose.yml

- name: Копировать nginx.conf
  copy:
    src: files/nginx.conf
    dest: /opt/korotkosilka/nginx.conf

- name: Запустить сервисы через Docker Compose
  shell: docker-compose up -d --build
  args:
    chdir: /opt/korotkosilka
