- name: Создать директорию /opt/korotkosilka
  file:
    path: /opt/korotkosilka
    state: directory
    mode: 0755

- name: Создать директорию для сертификатов
  file:
    path: /opt/korotkosilka/certs
    state: directory
    mode: 0755

- name: Сгенерировать приватный ключ для сертификата
  command: openssl genrsa -out /opt/korotkosilka/certs/privkey.pem 2048
  args:
    creates: /opt/korotkosilka/certs/privkey.pem

- name: Сгенерировать самоподписанный сертификат
  command: >
    openssl req -x509 -new -nodes -key /opt/korotkosilka/certs/privkey.pem
    -sha256 -days 365
    -out /opt/korotkosilka/certs/fullchain.pem
    -subj "/CN=korotko.local"
  args:
    creates: /opt/korotkosilka/certs/fullchain.pem

- name: Установить права на сертификат
  file:
    path: /opt/korotkosilka/certs/fullchain.pem
    mode: '0644'

- name: Копировать исходники Frontend
  copy:
    src: ../../Frontend/
    dest: /opt/korotkosilka/Frontend/
    owner: root
    group: root
    mode: 0755

- name: Копировать исходники Backend
  copy:
    src: ../../Backend/
    dest: /opt/korotkosilka/Backend/
    owner: root
    group: root
    mode: 0755

- name: Копировать docker-compose файл
  copy:
    src: files/docker-compose.frontend_backend.yml
    dest: /opt/korotkosilka/docker-compose.yml

- name: Копировать nginx.conf
  copy:
    src: files/nginx.conf
    dest: /opt/korotkosilka/nginx.conf

- name: Запустить сервисы через Docker Compose
  shell: docker-compose up -d --build
  args:
    chdir: /opt/korotkosilka

- name: Показать логи всех контейнеров после деплоя
  shell: docker-compose logs --tail=50
  args:
    chdir: /opt/korotkosilka
  register: compose_logs

- name: Вывести логи контейнеров на экран
  debug:
    msg: '{{ compose_logs.stdout }}'
