global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['shortlink.local']
    metrics_path: /api/metrics
